# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/book-cmd

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/book-cmd

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/book-cmd/CMakeFiles /mnt/c/book-cmd/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/book-cmd/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named book

# Build rule for target.
book: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 book
.PHONY : book

# fast build rule for target.
book/fast:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/build
.PHONY : book/fast

book_man.o: book_man.cpp.o

.PHONY : book_man.o

# target to build an object file
book_man.cpp.o:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/book_man.cpp.o
.PHONY : book_man.cpp.o

book_man.i: book_man.cpp.i

.PHONY : book_man.i

# target to preprocess a source file
book_man.cpp.i:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/book_man.cpp.i
.PHONY : book_man.cpp.i

book_man.s: book_man.cpp.s

.PHONY : book_man.s

# target to generate assembly for a file
book_man.cpp.s:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/book_man.cpp.s
.PHONY : book_man.cpp.s

cmd.o: cmd.cpp.o

.PHONY : cmd.o

# target to build an object file
cmd.cpp.o:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/cmd.cpp.o
.PHONY : cmd.cpp.o

cmd.i: cmd.cpp.i

.PHONY : cmd.i

# target to preprocess a source file
cmd.cpp.i:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/cmd.cpp.i
.PHONY : cmd.cpp.i

cmd.s: cmd.cpp.s

.PHONY : cmd.s

# target to generate assembly for a file
cmd.cpp.s:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/cmd.cpp.s
.PHONY : cmd.cpp.s

file_control.o: file_control.cpp.o

.PHONY : file_control.o

# target to build an object file
file_control.cpp.o:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/file_control.cpp.o
.PHONY : file_control.cpp.o

file_control.i: file_control.cpp.i

.PHONY : file_control.i

# target to preprocess a source file
file_control.cpp.i:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/file_control.cpp.i
.PHONY : file_control.cpp.i

file_control.s: file_control.cpp.s

.PHONY : file_control.s

# target to generate assembly for a file
file_control.cpp.s:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/file_control.cpp.s
.PHONY : file_control.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/main.cpp.s
.PHONY : main.cpp.s

ui_control.o: ui_control.cpp.o

.PHONY : ui_control.o

# target to build an object file
ui_control.cpp.o:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/ui_control.cpp.o
.PHONY : ui_control.cpp.o

ui_control.i: ui_control.cpp.i

.PHONY : ui_control.i

# target to preprocess a source file
ui_control.cpp.i:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/ui_control.cpp.i
.PHONY : ui_control.cpp.i

ui_control.s: ui_control.cpp.s

.PHONY : ui_control.s

# target to generate assembly for a file
ui_control.cpp.s:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/ui_control.cpp.s
.PHONY : ui_control.cpp.s

user_man.o: user_man.cpp.o

.PHONY : user_man.o

# target to build an object file
user_man.cpp.o:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/user_man.cpp.o
.PHONY : user_man.cpp.o

user_man.i: user_man.cpp.i

.PHONY : user_man.i

# target to preprocess a source file
user_man.cpp.i:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/user_man.cpp.i
.PHONY : user_man.cpp.i

user_man.s: user_man.cpp.s

.PHONY : user_man.s

# target to generate assembly for a file
user_man.cpp.s:
	$(MAKE) -f CMakeFiles/book.dir/build.make CMakeFiles/book.dir/user_man.cpp.s
.PHONY : user_man.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... book"
	@echo "... edit_cache"
	@echo "... book_man.o"
	@echo "... book_man.i"
	@echo "... book_man.s"
	@echo "... cmd.o"
	@echo "... cmd.i"
	@echo "... cmd.s"
	@echo "... file_control.o"
	@echo "... file_control.i"
	@echo "... file_control.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... ui_control.o"
	@echo "... ui_control.i"
	@echo "... ui_control.s"
	@echo "... user_man.o"
	@echo "... user_man.i"
	@echo "... user_man.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

